### ISSUE TITLE
fcitx5 is causing telegram to freeze

### ISSUE THREAD

**Issue by cjc7373** [fcitx/fcitx5#880]
**Describe the bug**
I've done a quick search in fcitx5 and qt's issue tracker and didn't find anything. I wonder if I should report here or qt's side.

**To Reproduce**
1. open telegram
2. type anything
3. the telegram window freezes

**Desktop (please complete the following information):**
 - Desktop: KDE 5.27.8, qt 6.6.0
 - Display server type: Wayland

**Additional context**
<details>
  <summary>backtrace of telegram</summary>

```bash
(gdb) bt
#0  0x00007f96ad920f6f in __GI___poll (fds=fds@entry=0x7ffc5e143ef0, nfds=nfds@entry=1, timeout=timeout@entry=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f96b3138b5e in poll (__timeout=-1, __nfds=1, __fds=0x7ffc5e143ef0) at /usr/include/bits/poll2.h:39
#2  wl_display_poll (display=0x7f969d713000, events=1) at ../wayland-1.22.0/src/wayland-client.c:1914
#3  wl_display_dispatch_queue (queue=<optimized out>, display=<optimized out>) at ../wayland-1.22.0/src/wayland-client.c:1987
#4  wl_display_dispatch_queue (display=0x7f969d713000, queue=0x7f969d7130f0) at ../wayland-1.22.0/src/wayland-client.c:1960
#5  0x00007f969db9df05 in QtWaylandClient::QWaylandDisplay::blockingReadEvents() (this=0x7f969d6cac80)
    at /usr/src/debug/qt6-wayland/qtwayland-everywhere-src-6.6.0/src/client/qwaylanddisplay.cpp:565
#6  QtWaylandClient::QWaylandShmBackingStore::resize(QSize const&) (this=this@entry=0x7f969b6106e0, size=...)
    at /usr/src/debug/qt6-wayland/qtwayland-everywhere-src-6.6.0/src/client/qwaylandshmbackingstore.cpp:280
#7  0x00007f969dba0cf8 in QtWaylandClient::QWaylandShmBackingStore::ensureSize() (this=0x7f969b6106e0)
    at /usr/src/debug/qt6-wayland/qtwayland-everywhere-src-6.6.0/src/client/qwaylandshmbackingstore.cpp:197
#8  QtWaylandClient::QWaylandShmBackingStore::beginPaint(QRegion const&) (this=0x7f969b6106e0, region=...)
    at /usr/src/debug/qt6-wayland/qtwayland-everywhere-src-6.6.0/src/client/qwaylandshmbackingstore.cpp:172
#9  0x00007f96af2273b6 in QBackingStore::beginPaint(QRegion const&) (this=0x7f9654f34d30, region=<optimized out>)
    at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.0/src/gui/painting/qbackingstore.cpp:125
#10 0x00007f969dae76f4 in fcitx::FcitxCandidateWindow::renderNow() (this=this@entry=0x7f9613220580)
    at /usr/src/debug/fcitx5-qt/fcitx5-qt-5.1.1/qt6/platforminputcontext/fcitxcandidatewindow.cpp:140
#11 0x00007f969daeab84 in fcitx::FcitxCandidateWindow::updateClientSideUI(QList<fcitx::FcitxQtFormattedPreedit> const&, int, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtStringKeyValue> const&, int, int, bool, bool)
    (this=<optimized out>, preedit=<optimized out>, cursorpos=<optimized out>, auxUp=<optimized out>, auxDown=<optimized out>, candidates=<optimized out>, candidateIndex=0, layoutHint=0, hasPrev=false, hasNext=true) at /usr/src/debug/fcitx5-qt/fcitx5-qt-5.1.1/qt6/platforminputcontext/fcitxcandidatewindow.cpp:512
#12 0x00007f969dae4d5c in QtPrivate::FunctorCall<QtPrivate::IndexesList<0, 1, 2, 3, 4, 5, 6, 7, 8>, QtPrivate::List<QList<fcitx::FcitxQtFormattedPreedit> const&, int, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtStringKeyValue> const&, int, int, bool, bool>, void, void (fcitx::QFcitxPlatformInputContext::*)(QList<fcitx::FcitxQtFormattedPreedit> const&, int, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtStringKeyValue> const&, int, int, bool, bool)>::call(void (fcitx::QFcitxPlatformInputContext::*)(QList<fcitx::FcitxQtFormattedPreedit> const&, int, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtStringKeyValue> const&, int, int, bool, bool), fcitx::QFcitxPlatformInputContext*, void**)
    (arg=<optimized out>, o=<optimized out>, f=<optimized out>) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:142
#13 QtPrivate::FunctionPointer<void (fcitx::QFcitxPlatformInputContext::*)(QList<fcitx::FcitxQtFormattedPreedit> const&, int, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtStringKeyValue> const&, int, int, bool, bool)>::call<QtPrivate::List<QList<fcitx::FcitxQtFormattedPreedit> const&, int, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtStringKeyValue> const&, int, int, bool, bool>, void>(void (fcitx::QFcitxPlatformInputContext::*)(QList<fcitx::FcitxQtFormattedPreedit> const&, int, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtStringKeyValue> const&, int, int, bool, bool), fcitx::QFcitxPlatformInputContext*, void**) (arg=<optimized out>, o=<optimized out>, f=<optimized out>)
    at /usr/include/qt6/QtCore/qobjectdefs_impl.h:182
#14 QtPrivate::QCallableObject<void (fcitx::QFcitxPlatformInputContext::*)(QList<fcitx::FcitxQtFormattedPreedit> const&, int, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtStringKeyValue> const&, int, int, bool, bool), QtPrivate::List<QList<fcitx::FcitxQtFormattedPreedit> const&, int, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtStringKeyValue> const&, int, int, bool, bool>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=<optimized out>, this_=<optimized out>, r=<optimized out>, a=<optimized out>, ret=<optimized out>) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:520
#15 0x00007f96ae5b9a59 in QtPrivate::QSlotObjectBase::call(QObject*, void**)
    (a=0x7ffc5e144520, r=0x7f969d757a00, this=0x7f968fff7000, this=<optimized out>, r=<optimized out>, a=<optimized out>)
    at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.0/src/corelib/kernel/qobjectdefs_impl.h:433
#16 doActivate<false>(QObject*, int, void**) (sender=0x7f9632e32de0, signal_index=8, argv=0x7ffc5e144520)
    at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.0/src/corelib/kernel/qobject.cpp:4021
#17 0x00007f969dad2e3e in fcitx::HybridInputContext::updateClientSideUI(QList<fcitx::FcitxQtFormattedPreedit> const&, int, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtStringKeyValue> const&, int, int, bool, bool)
    (this=<optimized out>, _t1=<optimized out>, _t2=<optimized out>, _t3=<optimized out>, _t4=<optimized out>, _t5=<optimized out>, _t6=<optimized out>, _t7=<optimized out>, _t8=<optimized out>, _t9=<optimized out>)
    at /usr/src/debug/fcitx5-qt/fcitx5-qt-5.1.1/qt6/platforminputcontext/fcitx5platforminputcontextplugin-qt6_autogen/PS6VK7TWHL/moc_hybridinputcontext.cpp:469
#18 0x00007f969dadb38c in QtPrivate::FunctorCall<QtPrivate::IndexesList<0, 1, 2, 3, 4, 5, 6, 7, 8>, QtPrivate::List<QList<fcitx::FcitxQtFormattedPreedit> const&, int, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtStringKeyValue> const&, int, int, bool, bool>, void, void (fcitx::HybridInputContext::*)(QList<fcitx::FcitxQtFormattedPreedit> const&, int, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtStringKeyValue> const&, int, int, bool, bool)>::call(void (fcitx::HybridInputContext::*)(QList<fcitx::FcitxQtFormattedPreedit> const&, int, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtStringKeyValue> const&, int, int, bool, bool), fcitx::HybridInputContext*, void**)
--Type <RET> for more, q to quit, c to continue without paging--c
    (arg=<optimized out>, o=<optimized out>, f=<optimized out>) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:142
#19 QtPrivate::FunctionPointer<void (fcitx::HybridInputContext::*)(QList<fcitx::FcitxQtFormattedPreedit> const&, int, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtStringKeyValue> const&, int, int, bool, bool)>::call<QtPrivate::List<QList<fcitx::FcitxQtFormattedPreedit> const&, int, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtStringKeyValue> const&, int, int, bool, bool>, void>(void (fcitx::HybridInputContext::*)(QList<fcitx::FcitxQtFormattedPreedit> const&, int, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtStringKeyValue> const&, int, int, bool, bool), fcitx::HybridInputContext*, void**) (arg=<optimized out>, o=<optimized out>, f=<optimized out>) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:182
#20 QtPrivate::QCallableObject<void (fcitx::HybridInputContext::*)(QList<fcitx::FcitxQtFormattedPreedit> const&, int, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtStringKeyValue> const&, int, int, bool, bool), QtPrivate::List<QList<fcitx::FcitxQtFormattedPreedit> const&, int, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtStringKeyValue> const&, int, int, bool, bool>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=<optimized out>, this_=<optimized out>, r=<optimized out>, a=<optimized out>, ret=<optimized out>) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:520
#21 0x00007f96ae5b9a59 in QtPrivate::QSlotObjectBase::call(QObject*, void**)
    (a=0x7ffc5e1446b0, r=0x7f9632e32de0, this=0x7f96928622c0, this=<optimized out>, r=<optimized out>, a=<optimized out>)
    at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.0/src/corelib/kernel/qobjectdefs_impl.h:433
#22 doActivate<false>(QObject*, int, void**) (sender=0x7f9692862120, signal_index=8, argv=0x7ffc5e1446b0)
    at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.0/src/corelib/kernel/qobject.cpp:4021
#23 0x00007f969da3753e in fcitx::FcitxQtInputContextProxy::updateClientSideUI(QList<fcitx::FcitxQtFormattedPreedit> const&, int, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtStringKeyValue> const&, int, int, bool, bool)
    (this=<optimized out>, _t1=<optimized out>, _t2=<optimized out>, _t3=<optimized out>, _t4=<optimized out>, _t5=<optimized out>, _t6=<optimized out>, _t7=<optimized out>, _t8=<optimized out>, _t9=<optimized out>) at /usr/src/debug/fcitx5-qt/fcitx5-qt-5.1.1/qt6/dbusaddons/Fcitx5Qt6DBusAddons_autogen/EWIEGA46WW/moc_fcitxqtinputcontextproxy.cpp:721
#24 0x00007f969da56dac in QtPrivate::FunctorCall<QtPrivate::IndexesList<0, 1, 2, 3, 4, 5, 6, 7, 8>, QtPrivate::List<QList<fcitx::FcitxQtFormattedPreedit>, int, QList<fcitx::FcitxQtFormattedPreedit>, QList<fcitx::FcitxQtFormattedPreedit>, QList<fcitx::FcitxQtStringKeyValue>, int, int, bool, bool>, void, void (fcitx::FcitxQtInputContextProxy::*)(QList<fcitx::FcitxQtFormattedPreedit> const&, int, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtStringKeyValue> const&, int, int, bool, bool)>::call(void (fcitx::FcitxQtInputContextProxy::*)(QList<fcitx::FcitxQtFormattedPreedit> const&, int, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtStringKeyValue> const&, int, int, bool, bool), fcitx::FcitxQtInputContextProxy*, void**) (arg=<optimized out>, o=<optimized out>, f=<optimized out>)
    at /usr/include/qt6/QtCore/qobjectdefs_impl.h:142
#25 QtPrivate::FunctionPointer<void (fcitx::FcitxQtInputContextProxy::*)(QList<fcitx::FcitxQtFormattedPreedit> const&, int, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtStringKeyValue> const&, int, int, bool, bool)>::call<QtPrivate::List<QList<fcitx::FcitxQtFormattedPreedit>, int, QList<fcitx::FcitxQtFormattedPreedit>, QList<fcitx::FcitxQtFormattedPreedit>, QList<fcitx::FcitxQtStringKeyValue>, int, int, bool, bool>, void>(void (fcitx::FcitxQtInputContextProxy::*)(QList<fcitx::FcitxQtFormattedPreedit> const&, int, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtStringKeyValue> const&, int, int, bool, bool), fcitx::FcitxQtInputContextProxy*, void**) (arg=<optimized out>, o=<optimized out>, f=<optimized out>) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:182
#26 QtPrivate::QCallableObject<void (fcitx::FcitxQtInputContextProxy::*)(QList<fcitx::FcitxQtFormattedPreedit> const&, int, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtFormattedPreedit> const&, QList<fcitx::FcitxQtStringKeyValue> const&, int, int, bool, bool), QtPrivate::List<QList<fcitx::FcitxQtFormattedPreedit>, int, QList<fcitx::FcitxQtFormattedPreedit>, QList<fcitx::FcitxQtFormattedPreedit>, QList<fcitx::FcitxQtStringKeyValue>, int, int, bool, bool>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*)
    (which=<optimized out>, this_=<optimized out>, r=<optimized out>, a=<optimized out>, ret=<optimized out>) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:520
#27 0x00007f96ae5b9a59 in QtPrivate::QSlotObjectBase::call(QObject*, void**)
    (a=0x7ffc5e144840, r=0x7f9692862120, this=0x7f968ff8afc0, this=<optimized out>, r=<optimized out>, a=<optimized out>)
    at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.0/src/corelib/kernel/qobjectdefs_impl.h:433
#28 doActivate<false>(QObject*, int, void**) (sender=0x7f969238aa00, signal_index=8, argv=0x7ffc5e144840)
    at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.0/src/corelib/kernel/qobject.cpp:4021
#29 0x00007f969da378fe in fcitx::FcitxQtInputContextProxyImpl::UpdateClientSideUI(QList<fcitx::FcitxQtFormattedPreedit>, int, QList<fcitx::FcitxQtFormattedPreedit>, QList<fcitx::FcitxQtFormattedPreedit>, QList<fcitx::FcitxQtStringKeyValue>, int, int, bool, bool)
    (this=this@entry=0x7f969238aa00, _t1=..., _t2=<optimized out>, _t3=..., _t4=..., _t5=..., _t6=<optimized out>, _t7=<optimized out>, _t8=<optimized out>, _t9=<optimized out>)
    at /usr/src/debug/fcitx5-qt/fcitx5-qt-5.1.1/qt6/dbusaddons/Fcitx5Qt6DBusAddons_autogen/EWIEGA46WW/moc_fcitxqtinputcontextproxyimpl.cpp:679
#30 0x00007f969da3d523 in fcitx::FcitxQtInputContextProxyImpl::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)
    (_o=0x7f969238aa00, _c=<optimized out>, _id=<optimized out>, _a=0x7ffc5e144b68) at /usr/include/qt6/QtCore/qarraydata.h:52
#31 0x00007f969da3f7c3 in fcitx::FcitxQtInputContextProxyImpl::qt_metacall(QMetaObject::Call, int, void**)
    (this=0x7f969238aa00, _c=QMetaObject::InvokeMetaMethod, _id=5, _a=0x7ffc5e144b68)
    at /usr/src/debug/fcitx5-qt/fcitx5-qt-5.1.1/qt6/dbusaddons/Fcitx5Qt6DBusAddons_autogen/EWIEGA46WW/moc_fcitxqtinputcontextproxyimpl.cpp:631
#32 0x00007f96b2727e4e in QDBusConnectionPrivate::deliverCall(QObject*, int, QDBusMessage const&, QList<QMetaType> const&, int)
    (this=0x7f969b61a540, object=0x7f969238aa00, msg=..., metaTypes=<optimized out>, slotIdx=11) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.0/src/dbus/qdbusintegrator.cpp:967
#33 0x00007f96ae5a5077 in QObject::event(QEvent*) (this=0x7f969238aa00, e=0x7f969b6b95c0) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.0/src/corelib/kernel/qobject.cpp:1437
#34 0x00007f96b037318b in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=this@entry=0x7f969d63b000, receiver=receiver@entry=0x7f969238aa00, e=e@entry=0x7f969b6b95c0)
    at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.0/src/widgets/kernel/qapplication.cpp:3290
#35 0x00007f96b0374ec9 in QApplication::notify(QObject*, QEvent*) (this=this@entry=0x7ffc5e145490, receiver=receiver@entry=0x7f969238aa00, e=e@entry=0x7f969b6b95c0)
    at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.0/src/widgets/kernel/qapplication.cpp:3052
#36 0x000055ee9e386e1f in Core::Sandbox::notifyOrInvoke(QObject*, QEvent*) (e=0x7f969b6b95c0, receiver=0x7f969238aa00, this=0x7ffc5e145490)
    at /usr/src/debug/telegram-desktop/tdesktop-4.10.3-full/Telegram/SourceFiles/core/sandbox.cpp:599
#37 Core::Sandbox::notify(QObject*, QEvent*) (this=0x7ffc5e145490, receiver=0x7f969238aa00, e=0x7f969b6b95c0)
    at /usr/src/debug/telegram-desktop/tdesktop-4.10.3-full/Telegram/SourceFiles/core/sandbox.cpp:615
#38 0x00007f96ae5626d8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x7f969238aa00, event=event@entry=0x7f969b6b95c0)
    at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.0/src/corelib/kernel/qcoreapplication.cpp:1118
#39 0x00007f96ae562a5b in QCoreApplication::sendEvent(QObject*, QEvent*) (event=0x7f969b6b95c0, receiver=<optimized out>)
    at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.0/src/corelib/kernel/qcoreapplication.cpp:1536
#40 QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (receiver=0x0, event_type=0, data=0x7f969d680b60)
    at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.0/src/corelib/kernel/qcoreapplication.cpp:1898
#41 0x00007f96ae799d24 in QCoreApplication::sendPostedEvents(QObject*, int) (receiver=0x0, event_type=0)
    at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.0/src/corelib/kernel/qcoreapplication.cpp:1757
#42 postEventSourceDispatch(GSource*, GSourceFunc, gpointer) (s=0x7f969d73ef40) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.0/src/corelib/kernel/qeventdispatcher_glib.cpp:243
#43 0x00007f96b010df19 in g_main_dispatch (context=0x7f969b601180) at ../glib/glib/gmain.c:3476
#44 0x00007f96b016c2b7 in g_main_context_dispatch_unlocked (context=0x7f969b601180) at ../glib/glib/gmain.c:4284
#45 g_main_context_iterate_unlocked.isra.0 (context=context@entry=0x7f969b601180, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/glib/gmain.c:4349
#46 0x00007f96b010c112 in g_main_context_iteration (context=0x7f969b601180, may_block=1) at ../glib/glib/gmain.c:4414
#47 0x00007f96ae797934 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x7f969d726460, flags=...)
    at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.0/src/corelib/kernel/qeventdispatcher_glib.cpp:393
#48 0x00007f96ae56cc5e in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (flags=..., this=0x7ffc5e145210)
    at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.0/src/corelib/kernel/qeventloop.cpp:100
#49 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x7ffc5e145210, flags=...)
    at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.0/src/corelib/kernel/qeventloop.cpp:182
#50 0x00007f96ae565178 in QCoreApplication::exec() () at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.0/src/corelib/global/qflags.h:74
#51 0x00007f96b036fd1a in QApplication::exec() () at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.6.0/src/widgets/kernel/qapplication.cpp:2569
#52 0x000055ee9e39f382 in Core::Sandbox::start() (this=0x7ffc5e145490) at /usr/src/debug/telegram-desktop/tdesktop-4.10.3-full/Telegram/SourceFiles/core/sandbox.cpp:181
#53 Core::Launcher::executeApplication() (this=this@entry=0x7f969d680de0) at /usr/src/debug/telegram-desktop/tdesktop-4.10.3-full/Telegram/SourceFiles/core/launcher.cpp:578
#54 0x000055ee9e3a03c4 in Core::Launcher::exec() (this=0x7f969d680de0) at /usr/src/debug/telegram-desktop/tdesktop-4.10.3-full/Telegram/SourceFiles/core/launcher.cpp:388
#55 0x000055ee9d5d3568 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/telegram-desktop/tdesktop-4.10.3-full/Telegram/SourceFiles/main.cpp:12

```
</details>

**Comment by wengxt** [comment]
can't reproduce, what's the distro you are using?

Also as a way that will not trigger this code path:
unset QT_IM_MODULE, select fcitx5 in the system settings -> virtual keyboard
https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#KDE_Plasma

it will use wayland input method protocol instead
